---
title: "Connectives + QUD Study: Force Choice"
author: Morgan Moyer
date: July 12, 2022
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73","#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00","#009E73")
```

```{r set wd and read in all the data, include=FALSE, warning=FALSE, echo=FALSE, message=FALSE}
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")

s <- read.csv("../01_pilot-SpecificQUD/data/processed.csv")
s$QUDType <- "Specific"

s$response <- as.factor(s$response)
s <- s %>% 
  mutate(response = recode(response, F = 1, J = 0))


g <- read.csv("../02_pilot-GeneralQUD/data/processed.csv")
g$QUDType <- "General"
g$response <- as.factor(g$response)
g <- g %>% 
  mutate(response = recode(response, F = 0, J = 1))

n <- read.csv("../03_pilot-NoQUD/data/processed.csv")
n$QUDType <- "None"
n$response <- as.factor(n$response)
n <- n %>% 
  mutate(response = recode(response, F = 1, J = 0))

d <- rbind(s,g,n)
names(d)
d$DecisionRT <- as.numeric(d$DecisionRT)
```

```{r}
names(d)
nrow(d) #3426

length(unique(d$ID)) # 60 --> 48
```

# add the mention/not mention factor
```{r}
d$Mention <- ""
d$Mention[(d$Number == "1") |
            (d$Number == "2") |
            (d$Number == "7") |
            (d$Number == "8")] <- "Mentioned"

d$Mention[(d$Number == "3") |
            (d$Number == "4") |
            (d$Number == "5") |
            (d$Number == "6") |
            (d$Number == "9") |
            (d$Number == "10") |
            (d$Number == "11") |
            (d$Number == "12")] <- "NotMentioned"



d$AnswerQUDRelevant <- ""
d$AnswerQUDRelevant[(d$Number == "1") |
            (d$Number == "2") |
            (d$Number == "11") |
            (d$Number == "12")] <- "NotQUDRelevant"

d$AnswerQUDRelevant[(d$Number == "3") |
            (d$Number == "4") |
            (d$Number == "5") |
            (d$Number == "6") |
            (d$Number == "7") |
            (d$Number == "8") |
            (d$Number == "9") |
            (d$Number == "10")] <- "QUDRelevant"


names(d)
```

Proportion yes (pressing F)
```{r}
agr <- d %>%
  group_by(Conj,QUDType) %>%
  summarise(Proportion_Yes = mean(response), CILow = ci.low(response), CIHigh = ci.high(response)) %>%
  mutate(YMin = Proportion_Yes - CILow, YMax = Proportion_Yes)

dodge = position_dodge(.9)
ggplot(agr, aes(Conj,y=Proportion_Yes,fill=QUDType)) +
  geom_bar(position=dodge,stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge) +
  # facet_wrap(~WhichQuestion) +
  # scale_fill_grey() +
  ggtitle(label = "Proportion Yes") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ylim(0,1)

```

# Mention
```{r}
agr <- d %>% 
  group_by(Conj,QUDType,Mention) %>%
  summarise(Proportion_Yes = mean(response), CILow = ci.low(response), CIHigh = ci.high(response)) %>%
  mutate(YMin = Proportion_Yes - CILow, YMax = Proportion_Yes)

dodge = position_dodge(.9)
ggplot(agr, aes(Conj,y=Proportion_Yes,fill=QUDType)) +
  geom_bar(position=dodge,stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge) +
  facet_wrap(~Mention) +
  # scale_fill_grey() +
  ggtitle(label = "Proportion Yes") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ylim(0,1)
```

# AnswerQUDRelevant
```{r}
agr <- d %>% 
  group_by(Conj,QUDType,AnswerQUDRelevant) %>%
  summarise(Proportion_Yes = mean(response), CILow = ci.low(response), CIHigh = ci.high(response)) %>%
  mutate(YMin = Proportion_Yes - CILow, YMax = Proportion_Yes)

dodge = position_dodge(.9)
ggplot(agr, aes(Conj,y=Proportion_Yes,fill=QUDType)) +
  geom_bar(position=dodge,stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge) +
  facet_wrap(~AnswerQUDRelevant) +
  # scale_fill_grey() +
  ggtitle(label = "Proportion Yes") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ylim(0,1)
```

# Negation
```{r}
agr <- d %>% 
  group_by(Conj,QUDType,Negation) %>%
  summarise(Proportion_Yes = mean(response), CILow = ci.low(response), CIHigh = ci.high(response)) %>%
  mutate(YMin = Proportion_Yes - CILow, YMax = Proportion_Yes)

dodge = position_dodge(.9)
ggplot(agr, aes(Conj,y=Proportion_Yes,fill=QUDType)) +
  geom_bar(position=dodge,stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge) +
  facet_wrap(~Negation) +
  # scale_fill_grey() +
  ggtitle(label = "Proportion Yes") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ylim(0,1)
```


# AnswerQUDRelevant x Mention
```{r}
agr <- d %>% 
  group_by(Conj,QUDType,AnswerQUDRelevant,Mention) %>%
  summarise(Proportion_Yes = mean(response), CILow = ci.low(response), CIHigh = ci.high(response)) %>%
  mutate(YMin = Proportion_Yes - CILow, YMax = Proportion_Yes)

dodge = position_dodge(.9)
ggplot(agr, aes(Conj,y=Proportion_Yes,fill=QUDType)) +
  geom_bar(position=dodge,stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge) +
  facet_grid(Mention~AnswerQUDRelevant) +
  # scale_fill_grey() +
  ggtitle(label = "Proportion Yes") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ylim(0,1)
```

# Items
```{r, fig.width=10,fig.height=5}
agr <- d %>% 
  group_by(QUDType,Number) %>%
  summarise(Proportion_Yes = mean(response), CILow = ci.low(response), CIHigh = ci.high(response)) %>%
  mutate(YMin = Proportion_Yes - CILow, YMax = Proportion_Yes)

dodge = position_dodge(.9)
ggplot(agr, aes(QUDType,y=Proportion_Yes,fill=QUDType)) +
  geom_bar(position=dodge,stat="identity") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=dodge) +
  facet_wrap(~Number,ncol=2) +
  # scale_fill_grey() +
  ggtitle(label = "Proportion Yes") +
  theme(plot.title = element_text(hjust = 0.5)) +
  ylim(0,1)
```
