---
title: "Exploratory analysis"
author: Morgan Moyer
date: 7 Nov, 2022
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(philentropy)
library(stringr)
library(textstem)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
```

```{r read in all the data, include=FALSE, warning=FALSE, echo=FALSE, message=FALSE}
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)

s <- read.csv("../../01_experiment_specific/data/processed.csv")
g <- read.csv("../../02_experiment_general/data/processed.csv")
n <- read.csv("../../03_experiment_noqud/data/processed.csv")

df <- rbind(s,g,n)

d <- df %>% filter(TrialType == "test")
```



```{r}
range(d$chunk1)


```


```{r}
d$QUDType <- as.factor(d$QUDType)
d$Conj <- as.factor(d$Conj)
d$Letters <- as.factor(d$Letters)
d$ID.Ibex <- as.factor(d$ID.Ibex)
d$SentType <- as.factor(d$SentType)
View(d)
# set QUD contrasts so that noqud is intercept
contrasts(d$QUDType)
# default:
#          NoQUD Specific
# General      0        0
# NoQUD        1        0
# Specific     0        1

contrasts(d$QUDType) = cbind("General.vs.NoQUD"=c(1,0,0),"Specific.vs.NoQUD"=c(0,0,1))
contrasts(d$QUDType)
```

# Interaction between Conj and QUDType?
- no....

## Chunk1
- no
```{r}

centered <- d %>% 
  mutate(cConj = as.numeric(Conj)-mean(as.numeric(Conj)))

m.c1 = lmer(chunk1 ~ cConj*QUDType + (1+cConj|ID.Ibex) + (1+QUDType|Letters), data=centered)
summary(m.c1)

plot(m.c1)
```


## Chunk1 log RT
- no
```{r}

centered <- d %>% 
  mutate(cConj = as.numeric(Conj)-mean(as.numeric(Conj))) %>% 
  mutate(logRT = log(chunk1))

m.c1.logrt = lmer(logRT ~ cConj*QUDType + (1+cConj|ID.Ibex) + (1+QUDType|Letters), data=centered)
summary(m.c1.logrt)

plot(m.c1)
```

## Chunk2
- yes
```{r}

centered <- d %>% 
  mutate(cConj = as.numeric(Conj)-mean(as.numeric(Conj)))

m.c2 = lmer(chunk2 ~ cConj*QUDType + (1+cConj|ID.Ibex) + (1+QUDType|Letters), data=centered)
summary(m.c2)

plot(m.c2)
```



# What about sentence type?
```{r}
centered <- d %>% 
  mutate(cConj = as.numeric(Conj)-mean(as.numeric(Conj)))

m.c1.st = lmer(chunk1 ~ cConj*QUDType*SentType + (1+cConj+SentType|ID.Ibex) + (1+QUDType|Letters), data=centered)
summary(m.c1.st)

plot(m)
```
